// CommonJS, every file is module (by default)
// Modules - Encapsulated Code (only share minimum)
const names = require('./4-name')
const sayHi = require('./5-utis')
const data = require('./6-alternativeWay')
require('./7-mindBurst')
sayHi('susan')
sayHi(names.john)
sayHi(names.peter)